### ISSUE TITLE
Question: is there any experience with Fritz!BOX current beta firmware

### ISSUE THREAD

**Issue by dp20eic** [karrot-dev/fritzinfluxdb#120]
Hello,
I would like to use the current beta firmware on my Fritz!BOX 7590, is there any experience whether 'fritzinfluxdb' is compatible with it?

https://avm.de/fritz-labor/frisch-aus-der-entwicklung/frisch-aus-der-entwicklung/

With kind regards
Bernd

**Comment by falke9176** [comment]
Hallo Bernd,

There are no problems with the Labor FW.
fritzinfluxdb still working great.....

Greets
Sven
