### ISSUE TITLE
AVM removed Energiemonitor also in 7.62 for FritzBox 7690

### ISSUE THREAD

**Issue by ronaldn1969** [karrot-dev/fritzinfluxdb#132]
Hi @bb-Ricardo 

Same problem like in #129 ... I changed my 7590 to 7690 and find out, that i didn't get CPU, Temp and Memory. 
Could you please put the 7690 also on the "blacklist", until AVM relaunched the energiemonitor for 7690. They working on a redesign.

Best regards
Ronald

**Comment by bb-Ricardo** [comment]
Hi,

have you tried version 1.2.4? The fix was independent from the FritzBox type.

**Comment by ronaldn1969** [comment]
Great... Will try...

**Comment by ronaldn1969** [comment]
@bb-Ricardo... successful tested...

**Comment by xyrolaith** [comment]
Just a heads up. The recently released FritzOS 8.20 (at least on my 6591 Cable) brings back all energy information.
