### ISSUE TITLE
Possible to extend data collection of fritzOS?

### ISSUE THREAD

**Issue by jumbi77** [karrot-dev/fritzinfluxdb#21]
Hello,

first i'd like to thank you for **fritzinfluxdb** ! fritzinfluxdb already collects a lot of things but maybe it is possible to even extend it. I just wanted to mention some metrics which would be nice.

Display metrics like the "Online-Monitor" on fritzOS. For e.g. "used DNS server IP", "number of connected VPN users", "Status of DynDNS", "number of configurated ports".

<img width="946" alt="" src="https://user-images.githubusercontent.com/17503985/108905108-9b823e80-761f-11eb-8354-085cf5bfa72e.png">

Display metrics of the "energy monitor -> power consumption" in percentage like:

<img width="936" alt="" src="https://user-images.githubusercontent.com/17503985/108905825-77732d00-7620-11eb-80b2-4f97262c9440.png">

Display metrics of the "energy monitor -> statistics" in percentage like:

<img width="1015" alt="" src="https://user-images.githubusercontent.com/17503985/108905964-a25d8100-7620-11eb-81e8-036a7031bc9b.png">

Thanks anyway!

**Comment by bb-Ricardo** [comment]
Hi,

I would add this data, no problem. Can you try finding a representation here: https://avm.de/service/schnittstellen/ ?

We're using the TR-064 protocol. Almost all parameters within theses PDF documents can be added quite simply.

If this data is not exposed via TR-064 then It's not possible to write this data to Influx.

**Comment by jumbi77** [comment]
Thanks for the link.. i just took a look.

1. DDNS (DynDNS) infos can be queried with

- service: _X_AVM-DE_RemoteAccess_
- action: _GetDDNSInfo_
- args: see: https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_remoteSCPD.pdf

2. DNS Servers

- service: _WANPPPConnection_ or _WANIPConnection_ (WANPPP with dsl, WANIP with cable - see blue text https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wanpppconnSCPD.pdf)
- action: _X_GetDNSServers_
- Note: What i found weird tho, is that in the screenshot in post 1 we see dns 1.1.1.1 or 1.0.0.1, but when i query _WANIPConnection_ -> _X_GetDNSServers_ i got this result: .... 'NewDNSServers': '82.144.X.X, 82.145.X.X' .....
I guess that are the default DNS servers by ISP and not the actual used dns servers??! I am confused here.
(Info: same when i query _WANIPConn1_ with action _X_AVM_DE_GetDNSServer_)

3. In general service: _WANDSLInterfaceConfig_ - action: _GetStatisticsTotal_ also seems interesting to log in case any error will appear (https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/wandslifconfigSCPD.pdf)

**Comment by bb-Ricardo** [comment]
Thank you for looking into it.

1. can you add a new service to the config and see if it's collected properly

2. same here, would you be add a new service to the config?

3. I had the same issue. I tried to to get this data when I joined this project but could find any representation. And especially the power and the CPU/MEM values would be quite interesting to monitor.

4. I'm sure this data is already in the config
https://github.com/yunity/fritzinfluxdb/blob/aafc41faa9c98284f67961aad398af7edca9ce81/fritzinfluxdb.ini-sample#L66-L80

Can you give it a go?

**Comment by NodeLace** [comment]
I'am not used to the Fritz data structure, so hopefully this is not a dumb question:

Is it possible to extent the monitoring data to the connected DECT controller for the radiators (Smarthome feature from AVM)?

**Comment by ronaldn1969** [comment]
> I'am not used to the Fritz data structure, so hopefully this is not a dumb question:
> 
> Is it possible to extent the monitoring data to the connected DECT controller for the radiators (Smarthome feature from AVM)?

Hi... There are a lot parameter regarding Homeautomation / Homeplug and DECT... 

If you install fritzconnection on your system you can run it with **fritzconnection  -i FritzboxIP -u API-User -p API-User_Password -c** 

To get access you have to create an user on your FritzBox.

**Comment by bb-Ricardo** [comment]
> > I'am not used to the Fritz data structure, so hopefully this is not a dumb question:
> > Is it possible to extent the monitoring data to the connected DECT controller for the radiators (Smarthome feature from AVM)?
> 
> Hi... There are a lot parameter regarding Homeautomation / Homeplug and DECT...
> 
> If you install fritzconnection on your system you can run it with **fritzconnection -i FritzboxIP -u API-User -p API-User_Password -c**
> 
> To get access you have to create an user on your FritzBox.
> 
> Than you can add this to your ini.

Thank you for this info. We should probably add this as a description (on how to get from there to your ini settings) to the README.

**Comment by ronaldn1969** [comment]
> Thank you for this info. We should probably add this as a description (on how to get from there to your ini settings) to the README. 

I tried my best... feel free to use, add, change, discard, ... ;o)

But, I'm not sure, sometimes you used a ":1" like in [service3] service = WANCommonInterfaceConfig:1 and sometimes not, like in [service1] service = WANCommonIFC

The output from fritzconnetion shows in both cases a "1" and the end...
 
Service:            WANCommonIFC1
Service:            WANCommonInterfaceConfig1

so, if you know, when to use what, I'm quit interessed to know.

Best Regards
Ronald

```
After you installed fritzconnection (pip install fritzconnection) on your system, you can run it to find out, which parameters you are interested in.

fritzconnection -i host -u username -p password -c

Therefor you take the credentials form your ini.

[fritzbox]
host = 192.168.x.y
username = xxx
password = yyy

If you find an additional parameter, you have to check in your ini file if the related "Service" and "Action" already exist. if yes, you can add the value. If not, you have to add a new [serviceX] section.

Example with existing Service and Action:

Part of the fritzconnection output:

--- schnipp ---

Service:            WANCommonIFC1
Action:             GetAddonInfos
Parameters:

    Name                                  direction     data type

    NewByteSendRate                          out ->     ui4
    NewByteReceiveRate                       out ->     ui4
    NewPacketSendRate                        out ->     ui4
    NewPacketReceiveRate                     out ->     ui4
    NewTotalBytesSent                        out ->     ui4
    NewTotalBytesReceived                    out ->     ui4
    NewAutoDisconnectTime                    out ->     ui4
    NewIdleDisconnectTime                    out ->     ui4
    NewDNSServer1                            out ->     string
    NewDNSServer2                            out ->     string
    NewVoipDNSServer1                        out ->     string
    NewVoipDNSServer2                        out ->     string
	
--- schnapp ---


Part of the ini file:

--- schnipp ----

[service1]
service = WANCommonIFC
actions = GetAddonInfos
          GetCommonLinkProperties
value_instances = NewByteSendRate : sendrate
                  NewByteReceiveRate : receiverate
                  NewX_AVM_DE_TotalBytesSent64: totalbytessent64
                  NewX_AVM_DE_TotalBytesReceived64 : totalbytesreceived64
                  NewTotalBytesSent: totalbytessent
                  NewTotalBytesReceived : totalbytesreceived      
                  NewPacketSendRate : packetsendrate
                  NewPacketReceiveRate : packetreceiverate
                  NewLayer1DownstreamMaxBitRate : downstreammax
                  NewLayer1UpstreamMaxBitRate : upstreammax
                  NewPhysicalLinkStatus : physicallinkstatus
                  NewWANAccessType: physicallinktype
				  
--- schnapp ---

Service and Action already exist. So you only have to add the new parameter... for example DNSServer1 and 2

value_instances = NewByteSendRate : sendrate
                  NewByteReceiveRate : receiverate
                  NewX_AVM_DE_TotalBytesSent64: totalbytessent64
                  NewX_AVM_DE_TotalBytesReceived64 : totalbytesreceived64
                  NewTotalBytesSent: totalbytessent
                  NewTotalBytesReceived : totalbytesreceived      
                  NewPacketSendRate : packetsendrate
                  NewPacketReceiveRate : packetreceiverate
                  NewLayer1DownstreamMaxBitRate : downstreammax
                  NewLayer1UpstreamMaxBitRate : upstreammax
                  NewPhysicalLinkStatus : physicallinkstatus
                  NewWANAccessType: physicallinktype
				  NewDNSServer1 : dnsserver1
				  NewDNSServer2 : dnsserver2


If the service already exist, but the needed action is missing, so add the Action

[service1]
service = WANCommonIFC
actions = GetAddonInfos
          GetCommonLinkProperties
		  X_AVM_DE_GetIPTVInfos


In case, that Service and Action is missing, you have to add a new [service] section

[service10]
service = Time:1
actions = GetInfo
value_instances = NewNTPServer1 : ntpserver1
                  NewNTPServer2 : ntpserver2
				  NewCurrentLocalTime  : currentlocaltime
				  


If you decide, that you don't need a value inside the ini, you can delete the line or can use # in front of the value.
```

**Comment by bb-Ricardo** [comment]
Just a ping.

would you mind testing this new version and let me know what you think?: https://github.com/karrot-dev/fritzinfluxdb/tree/rewrite-adding-async

Thank you

**Comment by bb-Ricardo** [comment]
All this data is collected with upcoming version 1.0
