### ISSUE TITLE
docker build ended with Fatal Python error

### ISSUE THREAD

**Issue by ronaldn1969** [karrot-dev/fritzinfluxdb#26]
Hi Ricardo

After long time I had to rebuild fritzinfluxdb on my Pi and faced the following error, when I build the docker image.
Do you have any idea, why this happen?

Cheers
Ronald

pi@raspberrypi:/opt/fritzinfluxdb $ sudo docker build -t fritzinflux .
Sending build context to Docker daemon  441.3kB
Step 1/5 : FROM python:3.6-slim
 ---> 1a50a9863f2d
Step 2/5 : WORKDIR /app
 ---> Running in 969e024847c7
Removing intermediate container 969e024847c7
 ---> 591969feae3a
Step 3/5 : COPY . /app
 ---> d68c8219b413
Step 4/5 : RUN pip install --trusted-host pypi.python.org -r requirements.txt
 ---> Running in 2da3792dfc98
**Fatal Python error: Py_Initialize: can't initialize time
PermissionError: [Errno 1] Operation not permitted

Current thread 0xb6fc8010 (most recent call first):
Aborted (core  #dumped)
The command '/bin/sh -c pip install --trusted-host pypi.python.org -r requirements.txt' returned a non-zero code: 134**

**Comment by bb-Ricardo** [comment]
Hi, Ronald,

it might seem an issue with your docker installation. I can see you building it on a raspberry pi with ARM. I just tried it on my amd64 MacBook and it worked.
```
09:19 $ docker build -t fritzflux .
[+] Building 9.4s (9/9) FINISHED
 => [internal] load build definition from Dockerfile                                                                                                                                                                     0.0s
 => => transferring dockerfile: 381B                                                                                                                                                                                     0.0s
 => [internal] load .dockerignore                                                                                                                                                                                        0.0s
 => => transferring context: 2B                                                                                                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/python:3.6-slim                                                                                                                                                       2.0s
 => [internal] load build context                                                                                                                                                                                        0.1s
 => => transferring context: 405.25kB                                                                                                                                                                                    0.1s
 => [1/4] FROM docker.io/library/python:3.6-slim@sha256:a7989f57b5078eae628f484fc39e249c88fd3404427e100aabcc5c6bc07cc1e7                                                                                                 3.1s
 => => resolve docker.io/library/python:3.6-slim@sha256:a7989f57b5078eae628f484fc39e249c88fd3404427e100aabcc5c6bc07cc1e7                                                                                                 0.0s
 => => sha256:a7989f57b5078eae628f484fc39e249c88fd3404427e100aabcc5c6bc07cc1e7 1.86kB / 1.86kB                                                                                                                           0.0s
 => => sha256:85fd9e14a8be3db37a9bed2a3756005f4a82240b6999b6594e83beba380e60fb 1.37kB / 1.37kB                                                                                                                           0.0s
 => => sha256:dbf9deeb946991c412f1dd7c73cd4154e14f469a8993df92bd4aae0d524d7858 8.54kB / 8.54kB                                                                                                                           0.0s
 => => sha256:7c9d54bd144b6b064612a059b5b49c147c720e5bdae3b2d9fe2f0fabb89d6270 1.08MB / 1.08MB                                                                                                                           0.9s
 => => sha256:c864302cca0121fcf6839c3127d8bb31d198f64393655aea9d614dffe75d4368 9.74MB / 9.74MB                                                                                                                           2.2s
 => => sha256:ae2760d4fe3a826d21fb15c281d58025931e2473b4821177783086925d263f14 232B / 232B                                                                                                                               0.2s
 => => sha256:ee33e3ab63a2794c509a61b9f054e393f4ae004200b761b02196a1f479e78dd0 2.50MB / 2.50MB                                                                                                                           1.3s
 => => extracting sha256:7c9d54bd144b6b064612a059b5b49c147c720e5bdae3b2d9fe2f0fabb89d6270                                                                                                                                0.3s
 => => extracting sha256:c864302cca0121fcf6839c3127d8bb31d198f64393655aea9d614dffe75d4368                                                                                                                                0.5s
 => => extracting sha256:ae2760d4fe3a826d21fb15c281d58025931e2473b4821177783086925d263f14                                                                                                                                0.0s
 => => extracting sha256:ee33e3ab63a2794c509a61b9f054e393f4ae004200b761b02196a1f479e78dd0                                                                                                                                0.2s
 => [2/4] WORKDIR /app                                                                                                                                                                                                   0.1s
 => [3/4] COPY . /app                                                                                                                                                                                                    0.0s
 => [4/4] RUN pip install --trusted-host pypi.python.org -r requirements.txt                                                                                                                                             3.8s
 => exporting to image                                                                                                                                                                                                   0.3s
 => => exporting layers                                                                                                                                                                                                  0.3s
 => => writing image sha256:36b20e5bd5414ad56d90a2ccabdcbd43ab8847ac96ee8aaed4e7af144d3998c6                                                                                                                             0.0s
 => => naming to docker.io/library/fritzflux                                                                                                                                                                             0.0s

Use 'docker scan' to run Snyk tests against images to find vulnerabilities and learn how to fix them
```

I will try to get my old raspberry pi out again and try running it in docker there.

**Comment by ronaldn1969** [comment]
Hi Ricardo

Thanks for checking... It was not a problem to build a container with infux and grafana, so I didn't thought, it could be my docker installation.

Nevertheless, I reinstalled my RaspPI OS and tried again... And it looks like that I really have a problem with docker...

when I install docker, I get this message:

pi@raspberrypi:~ $ sudo curl -fsSL https://get.docker.com | sh
# Executing docker install script, commit: 93d2499759296ac1f9c510605fef85052a2c32be
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq apt-transport-https ca-certificates curl >/dev/null
+ sudo -E sh -c curl -fsSL "https://download.docker.com/linux/raspbian/gpg" | gpg --dearmor --yes -o /usr/share/keyrings/docker-archive-keyring.gpg
gpg: **WARNUNG: Unsicheres Besitzverhältnis des Home-Verzeichnis `/home/pi/.gnupg'**
+ sudo -E sh -c echo "deb [arch=armhf signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/raspbian buster stable" > /etc/apt/sources.list.d/docker.list
+ sudo -E sh -c apt-get update -qq >/dev/null
+ sudo -E sh -c DEBIAN_FRONTEND=noninteractive apt-get install -y -qq --no-install-recommends  docker-ce-cli docker-ce >/dev/null
E: **Sub-process /usr/bin/dpkg returned an error code (1)**

update && upgrade finished with...

docker-ce (5:20.10.10~3-0~raspbian-buster) wird eingerichtet ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xe" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
   Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Thu 2021-11-04 14:58:43 CET; 31ms ago
     Docs: https://docs.docker.com
  Process: 4102 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
 Main PID: 4102 (code=exited, status=1/FAILURE)
dpkg: Fehler beim Bearbeiten des Paketes docker-ce (--configure):
 »installiertes docker-ce-Skript des Paketes post-installation«-Unterprozess gab den Fehlerwert 1 zurück
 
 
 Fehler traten auf beim Bearbeiten von:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)

So I have to find out, why I'm not able to install docker properly...

Thanks 
Ronald

**Comment by bb-Ricardo** [comment]
can we close this issue?

**Comment by ronaldn1969** [comment]
sorry... yes... after reinstall everything is running well
