### ISSUE TITLE
High CPU Utilization and Temperature

### ISSUE THREAD

**Issue by ronaldn1969** [karrot-dev/fritzinfluxdb#34]
@bb-Ricardo 

Hi Ricardo 

First I thought, it could be related to my setup... Running InfluxDB v2, Grafana and Telegraf in separate Docker container and created a database inside the influx bucket to use InfluxQL. Therefore, I decide to switch back to InfluxDB v1.8 and created a Docker container which included all three programs. But still the same...

Now to the effect what shows up... Beside your FritzBox monitoring, I run Telegraf to monitor the Pi4 which is hosting the FritzBox monitoring. As long as I only open the row with the Pi metrics, the temperature and cpu utilization is "normal". as soon as I open the FritzBox overview row, the temperature and cpu utilization increase up to 82°C and 99%. Short after I close the FritzBox overview row, the temperature and cpu utilization fell down to normal.

Unfortunately I didn't had the Pi monitoring running with your old version, so I can't compare at the moment. Will try to make a setup on my old Pi3 to have a look.

But maybe you or someone else had saw this also. Could it be, that this is related to the [database structure](https://github.com/karrot-dev/fritzinfluxdb/issues/18#issuecomment-1086648045)?

![image](https://user-images.githubusercontent.com/76207586/165916972-ae630a26-89d1-46c0-97c3-b7e906ef54e9.png)
![image](https://user-images.githubusercontent.com/76207586/165917018-b51f0848-f2c1-426b-8e3b-4344261a28e3.png)

Edit:

Setup the old FritzBox version with TIG container on my Pi3. Now have to wait for some data and then I can check... ;o)

**Comment by bb-Ricardo** [comment]
Hello @ronaldn1969,

I noticed some similar issues that loading the dashboard got quite slow as soon as there was more data collected.

I would NOT think that this is an issue of fritzinfux and more a Influx/grafana issue.

First I blamed it on the shard group duration which was set to to something like 168 hours instead of 24. Now on creation of new buckets with the fritzinfluxdb they get set to 24H. -> https://github.com/karrot-dev/fritzinfluxdb/pull/33/commits/d3143338a6e35b7e9db16ca6450dd5c20c95c71d#diff-7e286a2207fa26a8ed2169a4f16250b27fb2564f10118236da39f3f7dc0ff006L210

 Maybe you can check the shard group duration for your bucket in influxdb.

**Comment by ronaldn1969** [comment]
Hi @bb-Ricardo 

Thanks for your information. I didn't run Influx v2 at the moment. I use InfluxDB v1.8.10 because I thought it could be, because I setup a database inside the bucket. This means, that I have the utilization and temperature problem with v1.8.10 and v2.22.2. 

I will now test with your former version of fritzinflux. It's now running and I will wait for some more data. Will come back then.

**Comment by ronaldn1969** [comment]
morning @bb-Ricardo 

after collecting data over the weekend and check this morning, I didn't faced the issue on my Pi3 with the former version of fritzinflux...

the data appears directly and no impact to cpu utilization and temperature...

![image](https://user-images.githubusercontent.com/76207586/166198338-f5b327ff-81de-43b2-8a97-309dd3461007.png)
 
it's looks like, that this is maybe related to the "disordered" database structure or the lua values. Is it possible for me, to switch off the lua services? are the lua values responsible for the disordered database structure or is this because of influxdb v2?

**Comment by bb-Ricardo** [comment]
you can disable the collection of the Lua values here: 
https://github.com/karrot-dev/fritzinfluxdb/blob/rewrite-adding-async/fritzinfluxdb.py#L96

Just comment it out and then the Lua data won't be requested.

**Comment by ronaldn1969** [comment]
> you can disable the collection of the Lua values here: https://github.com/karrot-dev/fritzinfluxdb/blob/rewrite-adding-async/fritzinfluxdb.py#L96
> 
> Just comment it out and then the Lua data won't be requested.

I will give it a try...

**Comment by ronaldn1969** [comment]
@bb-Ricardo 

Setup the latest version from Git and comment out L96. 

I got following message...

```
 2022-05-02 08:06:23,349 - INFO: Starting fritzinfluxdb v1.0.0-alpha2 (2022-04-11)
 2022-05-02 08:06:23,351 - INFO: Done reading config files
 2022-05-02 08:06:23,416 - INFO: Successfully parsed config
 2022-05-02 08:06:23,436 - INFO: Database 'fritzbox' not found, trying to create it
 2022-05-02 08:06:23,491 - INFO: Connection to InfluxDB 1.8.10 established and database present
 2022-05-02 08:06:25,644 - INFO: Successfully established FritzBox TR-069 session
 2022-05-02 08:06:26,093 - INFO: Successfully established FritzBox Lua session
 2022-05-02 08:06:26,093 - INFO: Successfully connected to FritzBox '192.168.178.1' (fritz.box) Model: FRITZ!Box 7590 - FW: 7.29
 2022-05-02 08:06:26,096 - INFO: Starting main loop
!! 2022-05-02 08:06:27,010 - INFO: Requested invalid action 'GetInfo' for service: WANIPConnection:1
!! 2022-05-02 08:06:27,010 - INFO: Querying action 'GetInfo' will be disabled
!! 2022-05-02 08:06:27,010 - INFO: All actions for service 'WANIPConnection:1' are unavailable. Disabling service.
```

I took a look inside my fritzconnection output and find following:

```
Service:            WANIPConnection1
Action:             GetInfo
Parameters:

    Name                                  direction     data type

    NewEnable                                out ->     boolean
    NewConnectionStatus                      out ->     string
    NewPossibleConnectionTypes               out ->     string
    NewConnectionType                        out ->     string
    NewName                                  out ->     string
    NewUptime                                out ->     ui4
    NewLastConnectionError                   out ->     string
    NewRSIPAvailable                         out ->     boolean
    NewNATEnabled                            out ->     boolean
    NewExternalIPAddress                     out ->     string
    NewDNSServers                            out ->     string
    NewMACAddress                            out ->     string
    NewConnectionTrigger                     out ->     string
    NewRouteProtocolRx                       out ->     string
    NewDNSEnabled                            out ->     boolean
    NewDNSOverrideAllowed                    out ->     boolean
```

Is this is related to ":" in between?

**Comment by bb-Ricardo** [comment]
Hi, this is a desired behaviour. `WANIPConnection` on works on FritzBoxes with a cable modem. Have to add a message that this is OK if the Model uses DSL and  vice versa.

**Comment by ronaldn1969** [comment]
oh... yes... Monday morning... I see... WANPPPConnection:1 is for my FB...

Even without the Lua Service the database is not like in the old version... Is still fragmented... Maybe this is the reason for the issue. with the old unfragmented database structure I didn't face the issue.  Could it be, that because of fragmentaion, Grafana/InfluxDB need more time and system ressources to display the data? 


Setup: act. Fritzinfluxdb, InfluxDB v1.8.10, Grafana 8.5.0

![image](https://user-images.githubusercontent.com/76207586/166207365-5c7d11bf-7c78-48d8-94f8-41762bba1815.png)

**Comment by bb-Ricardo** [comment]
I wouldn't call it 'fragmented'. It is more accurate compared to the old method.

maybe this page has some hints: https://docs.influxdata.com/influxdb/v2.2/write-data/best-practices/

I could try to reduce the precision to "seconds" instead of "milliseconds"

**Comment by ronaldn1969** [comment]
okay... understand... but I'm running v1.8.10 not v2.2

> I could try to reduce the precision to "seconds" instead of "milliseconds"

if it's not to much for you... I'm here to test it...

**Comment by bb-Ricardo** [comment]
It would reduce the points of data a bit. And it would be an easy change.

Ultimately I could reimplement the old behavior and could compare it as well.

**Comment by ronaldn1969** [comment]
> Ultimately I could reimplement the old behavior and could compare it as well.

this means, that the database structure would be se same as in the former version? If you don't mind, let us start with the first of your suggestions ;o) maybe this solves the issue... Thanks a lot for your work, it's a great project...

**Comment by bb-Ricardo** [comment]
I change the precision to "s" in the branch. Can you pull the the branch again and give it a try?

Thank you

**Comment by ronaldn1969** [comment]
> I change the precision to "s" in the branch. Can you pull the the branch again and give it a try?
> 
> Thank you

already did... now running the container... will come back to you later...

**Comment by ronaldn1969** [comment]
Today the dashboard get a little bit slower and the CPU Utilization is around 35% and Temperature increase aboz 10°C as log as I display the dashboard.

**Comment by ronaldn1969** [comment]
Hi Ricardo 

Unfortunately the issue is not solved by changing from ms to s....

![image](https://user-images.githubusercontent.com/76207586/166879022-62b414cb-d155-4eb9-8c81-fe144653dfb0.png)

**Comment by bb-Ricardo** [comment]
Can you check how the data looks like in the database now?

**Comment by ronaldn1969** [comment]
of course... looks like before... 

![image](https://user-images.githubusercontent.com/76207586/166899410-9b8563fd-7df4-40bb-9a58-e07e0aace829.png)

**Comment by bb-Ricardo** [comment]
when you look at the `time` column you can see that the precision is now down to seconds.
Your view results probably from the different tags attached to each measurement.

And if you disable the lua_connection now and leave it running?

**Comment by ronaldn1969** [comment]
![image](https://user-images.githubusercontent.com/76207586/166910144-0d243abe-c82d-4d31-a251-b7bceb62421b.png)

still some spaces

**Comment by ronaldn1969** [comment]
hi @bb-Ricardo 

checked today again... without Lua I have no temp and utilization issue...

![image](https://user-images.githubusercontent.com/76207586/167601743-26775fbe-31c6-4a16-ac51-4d6a4d2b1f3e.png)

**Comment by bb-Ricardo** [comment]
Hi,

Yes, that is correct. Just wanted to see if it improves the situation. Temp and cpu values are only available via LUa connection.

**Comment by ronaldn1969** [comment]
sorry... yes, what I want to say is, as log as I didn't collect Lua values, I didn't face the temperature and utilization issue, what I reported here. so, if I activate the Lua collection, I have the high temperature and utilization issue again.

**Comment by bb-Ricardo** [comment]
Ahh, you're talking about your Raspi? I thought you ment your FritzBox.

Would be interesting to know which query causes the issue. Maybe I did something wrong creating the panels.

**Comment by ronaldn1969** [comment]
Yes... talking about Raspi... It happens already with this open row...

![image](https://user-images.githubusercontent.com/76207586/167623355-58221e08-deed-459f-aa7a-98bd396e0fd3.png)

and there are only three lua values... cpu temp, utilization and log... and I didn't belive, that there is something wrong in this panels... ;o)

But I can give it a tray... I switch on the lua collection and than run the dashboard without the lua panels. then we will see, what happens...

**Comment by bb-Ricardo** [comment]
Thank you for all the time and testing, this is highly valued.

**Comment by ronaldn1969** [comment]
morning Ricardo

It's in my own interest... And you did already a great job by publishing this project....

I took a look... The increase of temperature an utilization on the Raspi is not related to lua panels. Even without I have the issue...

![image](https://user-images.githubusercontent.com/76207586/167799083-4e877acc-44a4-419b-b210-35925a1bc50d.png)

**Comment by ronaldn1969** [comment]
It's looks like, that it is a Lua based issue. Maybe because the database have a lot more rows per timestamp instead of the old version, were it have only one row per timestamp.

![image](https://user-images.githubusercontent.com/76207586/168240213-13aef512-c533-4f6c-9f2d-e5a4a55e7e41.png)

**Comment by bb-Ricardo** [comment]
Mmmmh, this is all not really good as it is a show stopper for the whole rewrite. I pretty much stopped now. Because if this continues then it is nice to have the values, you just can't look at them 🤷.

I'm out of ideas in how to enhance the data collection to not cause this issue.

**Comment by ronaldn1969** [comment]
hi @bb-Ricardo looks good... with the reduced lua values I didn't face the temp and utilization problem. for me it's fine and I close this case...

![image](https://user-images.githubusercontent.com/76207586/170948640-2bd3185a-22ac-47c5-953a-e716a8dda8a3.png)

**Comment by bb-Ricardo** [comment]
hey @ronaldn1969,

Thank you for testing and your encouraging words.

I might have found the issue with the high cpu utilisation. Can you pull the latest commits from the rewrite branch? I also added an updated dashboard with more information.

Thank you.

**Comment by ronaldn1969** [comment]
Hey @bb-Ricardo

Nice to hear. I will definitely do it. But I need a bit time, I have limited access to my pi at the moment. 

As soon as I set up the actual version I will give you a response.

BR
Ronald

**Comment by bb-Ricardo** [comment]
version 1.0.0 has been released

**Comment by ronaldn1969** [comment]
Hey @bb-Ricardo 

Faster as thought. Build a docker container with version 1.0.0 from rewrite-adding-async and launched on my RasPi... Will now collected a few days and will come back and give you an update.

**Comment by bb-Ricardo** [comment]
In the reamde is a link to an prebuilt container on hub.docker.com.

**Comment by ronaldn1969** [comment]
Hi @bb-Ricardo

Thanks for the hint, I saw it later in the readme. But no problem to build it myself...

**Comment by bb-Ricardo** [comment]
Now also multi arch linux

**Comment by ronaldn1969** [comment]
hi @bb-Ricardo, back from holiday and checking the cpu utilization and temperature from my pi after collecting 15 days data. both in normal condition and displaying of data is fast, when I switch between the sections or going back to dashboard.

looks like your adjustments were successful. thanks for your efforts and further development of the project.

![image](https://user-images.githubusercontent.com/76207586/175906670-ccc4e151-c679-4085-9ecd-928e5f1e5227.png)

**Comment by bb-Ricardo** [comment]
These are great news. Thank you for all your help and testing efforts. This was very valuable.
