### ISSUE TITLE
Some of the Panels within Dashboard displaying incorrect data

### ISSUE THREAD

**Issue by netcruiser2k10** [karrot-dev/fritzinfluxdb#36]
Its a long shot, being as there not been much activity on here for about a year.
But is there someone that can help ?

The System Uptime Panel and DSL Link Uptime panel box are displaying incorrect data. It is displaying a default of 1 month uptime even though its been up for more than 3 months. I restarted my router and it restarts to 0 then freezes at 1 month. Im gonna spin up another virtual machine to test it too see if ive got a faulty version of fritzconnection but wondering is anyone can shed any light on this.

I would also like to request info on how to add a box to say whether the DSL is up or not, a older project i tried from different program of collectd had it but dont know how to add it in to this.

**Comment by bb-Ricardo** [comment]
Hi,

The master branch is kind of obsolete and I'm currently working on a rewrite.

If you don't mind you can try this branch. But it is still under development: https://github.com/karrot-dev/fritzinfluxdb/tree/rewrite-adding-async

**Comment by netcruiser2k10** [comment]
Thank you for responding to my message. 

I will most definitely give the Branch suggested ago, am i assuming correctly that I am going to need to download the original MASTER and then change the branch to the one above and download the changes ? Ill figure out how to do it on Ubuntu if this is needed. Apologies for the questions I'm fairly new to GitHub lol.

Ill spin up a new LXC to try to avoid damaging the other one, and give it a try.

**Comment by ronaldn1969** [comment]
Hi 

on debian I use 

```
sudo git clone https://github.com/karrot-dev/fritzinfluxdb/
cd [fritzinfluxdb](url)
sudo git checkout rewrite-adding-async
```

be aware of a temperature an cpu untilization problem in the new version with lua values on a RasPi. take a look [here](https://github.com/karrot-dev/fritzinfluxdb/issues/34#issue-1220317293)

**Comment by netcruiser2k10** [comment]
Thanks info on how to change the branch of the build.

My current fritz box has failed on me and awaiting a newer model to arrive. I will then begin configuring the vm for the new branch.

**Comment by bb-Ricardo** [comment]
Oh, hope the new one survives longer.

I also (most likely) solved the issue about the high cpu utilization. So please give it a go once you got your new box

**Comment by bb-Ricardo** [comment]
Well, version 1.0.0 has just been released.

**Comment by netcruiser2k10** [comment]
hi, apologies for getting back after a while. i have tried to configure the fritzinfluxdb.ini but every time i do and then restart fritzinfluxdb and check its status it comes up saying its failed but cant see where there is anything wrong in the config file. i there something im missing ?

**Comment by bb-Ricardo** [comment]
Hi, can you post the full log output here. Then I might be able to tell you what's the issue.

Thank you very much.

**Comment by netcruiser2k10** [comment]
Hi

im not sure where to find the logs for this, could you tell me where i could find them for you

this is the response when i check on the status of it
(.venv) root@fritzinflux-newtest:/opt/fritzinfluxdb# sudo systemctl status fritzinfluxdb.service 
● fritzinfluxdb.service - Fritz to InfluxDB daemon
     Loaded: loaded (/etc/systemd/system/fritzinfluxdb.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Sun 2022-07-03 20:57:49 BST; 3s ago
    Process: 615 ExecStart=/opt/fritzinfluxdb/.venv/bin/python /opt/fritzinfluxdb/fritzinfluxdb.py -d (code=exited, status=1/FAILURE)
   Main PID: 615 (code=exited, status=1/FAILURE)
        CPU: 259ms

Jul 03 20:57:49 fritzinflux-newtest systemd[1]: fritzinfluxdb.service: Main process exited, code=exited, status=1/FAILURE
Jul 03 20:57:49 fritzinflux-newtest systemd[1]: fritzinfluxdb.service: Failed with result 'exit-code'.

**Comment by netcruiser2k10** [comment]
Ive Managed to get it to work now, mistake was that i assumed it would be like the older configuration where you didnt need authentication details for influxdbV1. have added them now and seems to be working.

Ill monitor it for now to see how it performs.

Thanks Again

**Comment by netcruiser2k10** [comment]
I know im reopening a old topic but it is semi related as i have noticed that the router and connection uptime figures are wrong again using both the master and the branch suggested further up.

I have just changed to the next-release branch as that seems to be the most upto date one, but now according to the status of fritzinflux it keeps failing and not running even though none of the actual settings have changed. Where do i find the logs so i can look further in to it ?
